server:
  port: ${SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE} # Se asegura de que cargue el perfil desde el .env si está configurado
    datasource:
      url: jdbc:mysql://localhost:3306/dev_db
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      org.hibernate.SQL: DEBUG

debug: ${DEBUG_MODE}
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"