server:
  port: ${SERVER_PORT:8080} 
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} 
    url: jdbc:postgresql://localhost:5432/Cuna
    username: ${DB_USER:postgres}
    password: ${DB_PASS:admi}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    level:
      org.hibernate.SQL: DEBUG

debug: ${DEBUG_MODE:true}
